version: '3'
services:
  db:
    image: mongo:3.6.4
    ports:
      - "27017:27017"
    env_file: ./.env
    volumes:
      - 'data-volume:/data/db'
    container_name: mongodb
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - RAILS_ENV=production
      - DB_RESET=false
    env_file: ./.env
    restart: always
#  nginx:
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile
#    links:
#      - rails
#    ports:
#      - "80:80"
#    environment:
#      - RAILS_HOST=rails
#      - RAILS_PORT=3000
#    restart: always

volumes:
  data-volume: