development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: drive_checker_development
      hosts:
        - localhost:27017
      options:
  options:

production:
  clients:
    default:
      database: drive_checker
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: drive_checker_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
